redis:
  host: "localhost"
  port: 6379
  password: ""

channels:
  - "channel1"
  - "channel2"

messages:
  reload: "&aSyncCommand configuration reloaded."
  usage: "&cUsage: /sync (Bukkit) or /syncb (Bungee) or /syncv (Velocity) <channel> <command>"
  noPermission: "&cYou do not have permission."
  commandSynced: "&aCommand synced to channel &e%s&a."